// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WQkhQMlVnbFcGZNRT5OBriQ89I1pCDM',
    appId: '1:999410684871:android:138d05924ae7a3a9d07fe2',
    messagingSenderId: '999410684871',
    projectId: 'rao-echo-app',
    storageBucket: 'rao-echo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWjpNtRaNUVIXyuIuuiIPFIxcjzMRrIKo',
    appId: '1:999410684871:ios:4bc04ac90b770099d07fe2',
    messagingSenderId: '999410684871',
    projectId: 'rao-echo-app',
    storageBucket: 'rao-echo-app.firebasestorage.app',
    iosBundleId: 'com.example.lostandfounf',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlk8iVKUNRX86jiqfu7shdvG-GSArs420',
    appId: '1:999410684871:web:f62357539515ae28d07fe2',
    messagingSenderId: '999410684871',
    projectId: 'rao-echo-app',
    authDomain: 'rao-echo-app.firebaseapp.com',
    storageBucket: 'rao-echo-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWjpNtRaNUVIXyuIuuiIPFIxcjzMRrIKo',
    appId: '1:999410684871:ios:4bc04ac90b770099d07fe2',
    messagingSenderId: '999410684871',
    projectId: 'rao-echo-app',
    storageBucket: 'rao-echo-app.firebasestorage.app',
    iosBundleId: 'com.example.lostandfounf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlk8iVKUNRX86jiqfu7shdvG-GSArs420',
    appId: '1:999410684871:web:6e577fcd78688d31d07fe2',
    messagingSenderId: '999410684871',
    projectId: 'rao-echo-app',
    authDomain: 'rao-echo-app.firebaseapp.com',
    storageBucket: 'rao-echo-app.firebasestorage.app',
  );

}